spring.application.name=online-shopping-cart-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/online_shopping_cart
spring.datasource.username=amansaifi
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
